"""Parser for Graphviz DOT files generated by jdeps.

Extracts Java class dependencies, filters packages, identifies unresolved deps.
"""
from __future__ import annotations
import os
import re
from collections import defaultdict
from typing import Dict, Set, Tuple

from .models import GraphSnapshot, Node, Edge

TRAILING_PAREN_PATTERN = re.compile(r"\s+\([^)]*\)$")
NOT_FOUND_PATTERN = re.compile(r"\s*\(not found\)$", re.IGNORECASE)
EDGE_PATTERN = re.compile(r'"([^"]+)"\s*->\s*"([^"]+)"\s*;')


class DotFileParser:
    """Parser for jdeps DOT files."""

    @staticmethod
    def parse_directory(dot_directory: str) -> GraphSnapshot:
        """Parse all .dot files in directory into graph snapshot."""
        if not os.path.isdir(dot_directory):
            raise FileNotFoundError(f"DOT directory not found: {dot_directory}")

        class_ids: Set[str] = set()
        unresolved_ids: Set[str] = set()
        edge_weights: Dict[Tuple[str, str], int] = defaultdict(int)

        for filename in os.listdir(dot_directory):
            if not filename.endswith(".dot"):
                continue
            file_path = os.path.join(dot_directory, filename)
            DotFileParser._parse_file(
                file_path, class_ids, unresolved_ids, edge_weights
            )

        return DotFileParser._build_snapshot(
            class_ids, unresolved_ids, edge_weights, dot_directory
        )

    @staticmethod
    def _parse_file(
            file_path: str,
            class_ids: Set[str],
            unresolved_ids: Set[str],
            edge_weights: Dict[Tuple[str, str], int],
    ) -> None:
        """Parse single DOT file."""
        with open(file_path, encoding="utf-8") as f:
            for line in f:
                match = EDGE_PATTERN.search(line)
                if not match:
                    continue

                raw_src, raw_tgt = match.group(1), match.group(2)
                src = DotFileParser._normalize_id(raw_src)
                tgt = DotFileParser._normalize_id(raw_tgt)

                # Filter: only class-to-class
                if not (DotFileParser._is_java_class(src) and
                        DotFileParser._is_java_class(tgt)):
                    continue

                class_ids.add(src)
                class_ids.add(tgt)

                if DotFileParser._is_unresolved(raw_src):
                    unresolved_ids.add(src)
                if DotFileParser._is_unresolved(raw_tgt):
                    unresolved_ids.add(tgt)

                edge_weights[(src, tgt)] += 1

    @staticmethod
    def _normalize_id(raw: str) -> str:
        """Remove trailing parentheses: 'Foo (jar)' -> 'Foo'."""
        return TRAILING_PAREN_PATTERN.sub("", raw).strip()

    @staticmethod
    def _is_unresolved(raw: str) -> bool:
        """Check if marked as '(not found)'."""
        return bool(NOT_FOUND_PATTERN.search(raw))

    @staticmethod
    def _extract_last_segment(fqn: str) -> str:
        """Get last segment: 'com/example/Foo' -> 'Foo'."""
        after_slash = fqn.rsplit("/", 1)[-1]
        return after_slash.rsplit(".", 1)[-1] if "." in after_slash else after_slash

    @staticmethod
    def _is_java_class(fqn: str) -> bool:
        """Heuristic: classes have uppercase or '$' (inner classes)."""
        last = DotFileParser._extract_last_segment(fqn)
        return "$" in last or any(c.isupper() for c in last)

    @staticmethod
    def _build_snapshot(
            class_ids: Set[str],
            unresolved_ids: Set[str],
            edge_weights: Dict[Tuple[str, str], int],
            source_dir: str,
    ) -> GraphSnapshot:
        """Build GraphSnapshot from parsed data."""
        nodes = [Node(id=cid, type="class") for cid in sorted(class_ids)]
        edges = [
            Edge(from_id=src, to_id=tgt, weight=w)
            for (src, tgt), w in edge_weights.items()
        ]

        meta = {
            "language": "java",
            "source": source_dir,
            "unresolvedIds": sorted(unresolved_ids),
            "filtered": "packages-removed",
        }

        return GraphSnapshot(nodes=nodes, edges=edges, meta=meta)