"""Parser for Graphviz DOT files generated by jdeps.

This module extracts Java class dependencies from DOT format files,
filtering out package-level nodes and identifying unresolved dependencies.
"""
from __future__ import annotations
import os
import re
from collections import defaultdict
from typing import Dict, Set, Tuple

from .models import GraphSnapshot, Node, Edge

# Regex patterns for parsing DOT files
TRAILING_PAREN_PATTERN = re.compile(r"\s+\([^)]*\)$")
NOT_FOUND_PATTERN = re.compile(r"\s*\(not found\)$", re.IGNORECASE)
EDGE_PATTERN = re.compile(r'"([^"]+)"\s*->\s*"([^"]+)"\s*;')


class DotFileParser:
    """Parser for extracting dependency graphs from jdeps DOT files."""

    @staticmethod
    def parse_directory(dot_directory: str) -> GraphSnapshot:
        """Parse all DOT files in a directory into a single graph snapshot.
        
        Args:
            dot_directory: Path to directory containing .dot files
            
        Returns:
            GraphSnapshot containing all parsed nodes and edges
            
        Raises:
            FileNotFoundError: If the directory doesn't exist
        """
        if not os.path.isdir(dot_directory):
            raise FileNotFoundError(f"DOT directory not found: {dot_directory}")

        class_ids: Set[str] = set()
        unresolved_ids: Set[str] = set()
        edge_weights: Dict[Tuple[str, str], int] = defaultdict(int)

        for filename in os.listdir(dot_directory):
            if not filename.endswith(".dot"):
                continue

            file_path = os.path.join(dot_directory, filename)
            DotFileParser._parse_file(
                file_path, class_ids, unresolved_ids, edge_weights
            )

        return DotFileParser._build_snapshot(
            class_ids, unresolved_ids, edge_weights, dot_directory
        )

    @staticmethod
    def _parse_file(
            file_path: str,
            class_ids: Set[str],
            unresolved_ids: Set[str],
            edge_weights: Dict[Tuple[str, str], int],
    ) -> None:
        """Parse a single DOT file and accumulate results."""
        with open(file_path, encoding="utf-8") as file:
            for line in file:
                match = EDGE_PATTERN.search(line)
                if not match:
                    continue

                raw_source, raw_target = match.group(1), match.group(2)
                source_id = DotFileParser._normalize_id(raw_source)
                target_id = DotFileParser._normalize_id(raw_target)

                # Only keep class-to-class dependencies (filter out packages)
                if not (DotFileParser._is_java_class(source_id) and
                        DotFileParser._is_java_class(target_id)):
                    continue

                class_ids.add(source_id)
                class_ids.add(target_id)

                if DotFileParser._is_unresolved(raw_source):
                    unresolved_ids.add(source_id)
                if DotFileParser._is_unresolved(raw_target):
                    unresolved_ids.add(target_id)

                edge_weights[(source_id, target_id)] += 1

    @staticmethod
    def _normalize_id(raw_label: str) -> str:
        """Remove trailing parenthetical information from node labels.
        
        Example: 'com.example.Foo (example.jar)' -> 'com.example.Foo'
        """
        return TRAILING_PAREN_PATTERN.sub("", raw_label).strip()

    @staticmethod
    def _is_unresolved(raw_label: str) -> bool:
        """Check if a node is marked as unresolved (not found)."""
        return bool(NOT_FOUND_PATTERN.search(raw_label))

    @staticmethod
    def _extract_last_segment(fully_qualified_name: str) -> str:
        """Extract the last segment from a fully qualified name.
        
        Example: 'com/example/Foo' -> 'Foo' or 'com.example.Bar' -> 'Bar'
        """
        after_slash = fully_qualified_name.rsplit("/", 1)[-1]
        return after_slash.rsplit(".", 1)[-1] if "." in after_slash else after_slash

    @staticmethod
    def _is_java_class(fully_qualified_name: str) -> bool:
        """Heuristic to determine if a name represents a Java class.
        
        Java classes typically:
        - Start with an uppercase letter
        - May contain '$' for inner classes
        
        This filters out package names which are typically all lowercase.
        """
        last_segment = DotFileParser._extract_last_segment(fully_qualified_name)
        return "$" in last_segment or any(char.isupper() for char in last_segment)

    @staticmethod
    def _build_snapshot(
            class_ids: Set[str],
            unresolved_ids: Set[str],
            edge_weights: Dict[Tuple[str, str], int],
            source_directory: str,
    ) -> GraphSnapshot:
        """Construct a GraphSnapshot from parsed data."""
        nodes = [Node(id=class_id, type="class") for class_id in sorted(class_ids)]

        edges = [
            Edge(from_id=source, to_id=target, weight=weight)
            for (source, target), weight in edge_weights.items()
        ]

        metadata = {
            "language": "java",
            "source": source_directory,
            "unresolvedIds": sorted(unresolved_ids),
            "filtered": "packages-removed",
        }

        return GraphSnapshot(nodes=nodes, edges=edges, meta=metadata)


# Convenience function for backward compatibility
def parse_dot_directory(dot_directory: str) -> GraphSnapshot:
    """Parse all DOT files in a directory into a graph snapshot.
    
    Args:
        dot_directory: Path to directory containing .dot files
        
    Returns:
        GraphSnapshot with all dependencies
    """
    return DotFileParser.parse_directory(dot_directory)